
text = "ZXMQBHVMXKXVSAVMKVQJXKXBGXLWHXNVVMTVTBBEXNTSXDSXTVXHXFAT\
BVMTVVMXITSXXNHQZXHJIVMXWSDSXTVQSZWVMDXSVTWNANTBWXNTJBXSWRMVK\
VMTVTEQNRVMXKXTSXBWGXBWJXSVITNHVMXCASKAWVQGMTCCWNXKKVMTVVQKXDAS\
XVMXKXSWRMVKRQLXSNEXNVKTSXWNKVWVAVXHTEQNREXNHXSWLWNRVMXWSPAKVCQZ\
XSKGSQEVMXDQNKXNVQGVMXRQLXSNXHVMTVZMXNXLXSTNIGQSEQGRQLXSNEXNVJXDQEX\
KHXKVSADVWLXQGVMXKXXNHKWVWKVMXSWRMVQGVMXCXQCBXVQTBVXSQSVQTJQBWKMWVT\
NHVQWNKVWVAVXNXZRQLXSNEXNVBTIWNRWVKGQANHTVWQNQNKADMCSWNDWCBXKTNHQSR\
TNWOWNRWVKCQZXSKWNKADMGQSETKVQVMXEKMTBBKXXEEQKVBWYXBIVQXGGXDVVMXWS\
KTGXVITNHMTCCWNXKKCSAHXNDXWNHXXHZWBBHWDVTVXVMTVRQLXSNEXNVKBQNRXKV\
TJBWKMXHKMQABHNQVJXDMTNRXHGQSBWRMVTNHVSTNKWXNVDTAKXKTNHTDDQSHWNR\
BITBBXUCXSWXNDXMTVMKMXZNVMTVETNYWNHTSXEQSXHWKCQKXHVQKAGGXSZMWBXX\
LWBKTSXKAGGXSTJBXVMTNVQSWRMVVMXEKXBLXKJITJQBWKMWNRVMXGQSEKVQZMWDM\
VMXITSXTDDAKVQEXHJAVZMXNTBQNRVSTWNQGTJAKXKTNHAKASCTVWQNKCASKAWNRW\
NLTSWTJBIVMXKTEXQJPXDVXLWNDXKTHXKWRNVQSXHADXVMXEANHXSTJKQBAVXHXKC\
QVWKEWVWKVMXWSSWRMVWVWKVMXWSHAVIVQVMSQZQGGKADMRQLXSNEXNVTNHVQCSQ\
LWHXNXZRATSHKGQSVMXWSGAVASXKXDASWVIKADMMTKJXXNVMXCTVWXNVKAGGXSTND\
XQGVMXKXDQBQNWXKTNHKADMWKNQZVMXNXDXKKWVIZMWDMDQNKVSTWNKVMXEVQTBVX\
SVMXWSGQSEXSKIKVXEKQGRQLXSNEXNVVMXMWKVQSIQGVMXCSXKXNVYWNRQGRSXTVJ\
SWVTWNWKTMWKVQSIQGSXCXTVXHWNPASWXKTNHAKASCTVWQNKTBBMTLWNRWNHWSXDVQ\
JPXDVVMXXKVTJBWKMEXNVQGTNTJKQBAVXVISTNNIQLXSVMXKXKVTVXKVQCSQLXVMWK\
BXVGTDVKJXKAJEWVVXHVQTDTNHWHZQSBH"

# freqString = "ETAOINSHRDLCUMWFGYPBVKJXQZ" # wikipedia
freqString = "ETAOINSRHDLUCMFYWGPBVKXQJZ" # cornell
#freqString = "ETAOINSHRDLCUMWFGYPBVKJXQZ"


inputMap = {}
outputMap = {}
plainText = ""
for c in text:
    if c in inputMap:
        inputMap[c] += 1
    else:
        inputMap[c] = 1
    
index = 0;  
charList = [] 
for c in sorted(inputMap.items(), key=lambda x: x[1], reverse=True):
    print(c)
    outputMap[c[0]] = freqString[index%26]
    print(outputMap[c[0]])
    index += 1

for c in text:
    charList.append(outputMap[c])

print("".join(charList))
